// @vitest-environment node
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import { EventEmitter } from 'events'
import { PassThrough } from 'stream'
import fs from 'fs'
import os from 'os'
import path from 'path'

const mocks = vi.hoisted(() => ({ spawn: vi.fn(), execFile: vi.fn(), directory: '' }))
vi.mock('electron', () => ({ app: { getPath: () => mocks.directory } }))
vi.mock('child_process', () => ({ spawn: mocks.spawn, execFile: mocks.execFile }))
vi.mock('./codex-cli', async importOriginal => ({ ...await importOriginal<typeof import('./codex-cli')>(), resolveCodexBinary: () => 'codex.exe' }))

function child() {
  return Object.assign(new EventEmitter(), { pid: 12345, stdout: new PassThrough(), stderr: new PassThrough(), stdin: new PassThrough(), kill: vi.fn() })
}

beforeEach(() => {
  vi.resetModules()
  mocks.spawn.mockReset()
  mocks.directory = fs.mkdtempSync(path.join(os.tmpdir(), 'chugnus-codex-test-'))
})
afterEach(() => fs.rmSync(mocks.directory, { recursive: true, force: true }))

describe('Codex session lifecycle', () => {
  it('streams split UTF-8, persists history and resumes the exact thread', async () => {
    const api = await import('./codex-sessions')
    const proc = child()
    mocks.spawn.mockReturnValue(proc)
    api.initCodexSessions({ isDestroyed: () => false, webContents: { send: vi.fn() } } as any)
    const opts = { projectPath: mocks.directory, prompt: 'hello', access: 'workspace-write' as const, model: 'catalog-model', effort: 'ultra' }
    const s = api.startCodexTurn(opts)
    proc.stdout.write('{"type":"thread.started","thread_id":"thread-123"}\n')
    const chunk = Buffer.from('{"type":"item.completed","item":{"id":"0","type":"agent_message","text":"Ready 🐇"}}\n')
    const split = chunk.indexOf(Buffer.from('🐇')) + 2
    proc.stdout.write(chunk.subarray(0, split)); proc.stdout.write(chunk.subarray(split))
    proc.stdout.write('{"type":"turn.completed","usage":{"input_tokens":10,"output_tokens":2}}')
    proc.emit('close', 0)
    expect(s.status).toBe('ready')
    expect(s.messages[0].state).toBe('completed')
    expect(s.messages[1].content).toBe('Ready 🐇')
    expect(JSON.parse(fs.readFileSync(path.join(mocks.directory, 'codex-sessions.json'), 'utf8'))[0].threadId).toBe('thread-123')
    mocks.spawn.mockReturnValue(child())
    api.startCodexTurn({ ...opts, sessionId: s.id, prompt: 'continue' })
    expect(mocks.spawn.mock.calls[1][1]).toEqual(expect.arrayContaining(['resume', 'thread-123']))
    api.startCodexTurn({ ...opts, sessionId: s.id, prompt: 'queued follow-up' })
    expect(s.pendingTurns?.[0].options.prompt).toBe('queued follow-up')
    expect(mocks.spawn).toHaveBeenCalledTimes(2)
  })
  it('reports an early CLI exit instead of waiting forever', async () => {
    const api = await import('./codex-sessions')
    const proc = child(); mocks.spawn.mockReturnValue(proc)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const s = api.startCodexTurn({ projectPath: mocks.directory, prompt: 'test', access: 'read-only' })
    proc.stderr.write('Please sign in'); proc.emit('close', 1)
    expect(s.status).toBe('error')
    expect(s.error).toContain('Please sign in')
    expect(s.messages[0].state).toBe('failed')
  })
  it('preserves corrupt history instead of silently overwriting it', async () => {
    const api = await import('./codex-sessions')
    const history = path.join(mocks.directory, 'codex-sessions.json')
    fs.writeFileSync(history, '{broken')
    api.initCodexSessions({ isDestroyed: () => true } as any)
    expect(() => api.getCodexSessions()).toThrow('preserved')
    expect(() => api.startCodexTurn({ projectPath: mocks.directory, prompt: 'test', access: 'read-only' })).toThrow('preserved')
    expect(fs.readFileSync(history, 'utf8')).toBe('{broken')
  })
  it('stops the process tree and ignores late completion events', async () => {
    const api = await import('./codex-sessions')
    const proc = child(); mocks.spawn.mockReturnValue(proc)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const s = api.startCodexTurn({ projectPath: mocks.directory, prompt: 'test', access: 'workspace-write' })
    api.stopCodexSession(s.id)
    if (process.platform === 'win32') expect(mocks.execFile).toHaveBeenCalledWith('taskkill', ['/pid', '12345', '/T', '/F'], { windowsHide: true }, expect.any(Function))
    proc.stdout.write('{"type":"turn.completed"}\n')
    proc.emit('close', 1)
    expect(s.status).toBe('stopped')
    expect(s.turns).toBe(0)
    expect(s.messages[0].state).toBe('interrupted')
    api.archiveCodexSession(s.id, true)
    expect(s.archived).toBe(true)
    api.archiveCodexSession(s.id, true, 'completed')
    expect(s.disposition).toBe('completed')
    api.archiveCodexSession(s.id, false)
    expect(s.disposition).toBeUndefined()
  })
})


describe('follow-up message queue', () => {
  it('runs messages once in FIFO order on the same thread with their chosen settings', async () => {
    const api = await import('./codex-sessions')
    const first = child(), second = child(), third = child()
    mocks.spawn.mockReturnValueOnce(first).mockReturnValueOnce(second).mockReturnValueOnce(third)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const opts = { projectPath: mocks.directory, prompt: 'first', access: 'workspace-write' as const }
    const session = api.startCodexTurn(opts)
    expect(session.messages[0].state).toBe('starting')
    first.stdout.write('{"type":"turn.started"}\n')
    expect(session.messages[0].state).toBe('working')
    first.stdout.write('{"type":"thread.started","thread_id":"queue-thread"}\n')
    api.startCodexTurn({ ...opts, sessionId: session.id, prompt: 'second', model: 'model-two', effort: 'max' })
    api.startCodexTurn({ ...opts, sessionId: session.id, prompt: 'third' })
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
    expect(session.pendingTurns?.map(item => item.options.prompt)).toEqual(['second', 'third'])
    const queuedId = session.pendingTurns![0].id
    expect(session.messages).toHaveLength(1)
    first.stdout.write('{"type":"turn.completed"}\n'); first.emit('close', 0)
    expect(session.messages.map(item => item.content)).toEqual(['first', 'second'])
    expect(session.messages[0].state).toBe('completed')
    expect(session.messages[1].state).toBe('starting')
    expect(session.messages[1].queuedId).toBe(queuedId)
    expect(mocks.spawn.mock.calls[1][1]).toEqual(expect.arrayContaining(['--model', 'model-two', 'model_reasoning_effort="max"', 'resume', 'queue-thread']))
    second.stdout.write('{"type":"turn.completed"}\n'); second.emit('close', 0)
    expect(session.messages.map(item => item.content)).toEqual(['first', 'second', 'third'])
    expect(session.pendingTurns).toEqual([])
    third.stdout.write('{"type":"turn.completed"}\n'); third.emit('close', 0)
    expect(session.status).toBe('ready')
    expect(mocks.spawn).toHaveBeenCalledTimes(3)
  })

  it('pauses queued messages on Stop and retains them over restart until explicitly resumed', async () => {
    let api = await import('./codex-sessions')
    const first = child()
    mocks.spawn.mockReturnValue(first)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const opts = { projectPath: mocks.directory, prompt: 'first', access: 'read-only' as const }
    const session = api.startCodexTurn(opts)
    api.startCodexTurn({ ...opts, sessionId: session.id, prompt: 'next' })
    api.stopCodexSession(session.id)
    first.emit('close', 1)
    expect(session.queuePaused).toBe(true)
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
    vi.resetModules()
    api = await import('./codex-sessions')
    api.initCodexSessions({ isDestroyed: () => true } as any)
    expect(api.getCodexSessions()[0].pendingTurns?.[0].options.prompt).toBe('next')
    expect(api.getCodexSessions()[0].queuePaused).toBe(true)
    expect(api.getCodexSessions()[0].messages[0].state).toBe('interrupted')
    await api.recoverCodexSessions()
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
    const resumed = child()
    mocks.spawn.mockReturnValue(resumed)
    api.controlCodexQueue(session.id, 'resume')
    await vi.waitFor(() => expect(mocks.spawn).toHaveBeenCalledTimes(2))
    expect(api.getCodexSessions()[0].messages.at(-1)?.content).toBe('first')
    resumed.stdout.write('{"type":"turn.completed"}\n'); resumed.emit('close', 0)
    expect(api.getCodexSessions()[0].messages.at(-1)?.content).toBe('next')
  })

  it('retains follow-ups on a failed turn and lets the user remove them', async () => {
    const api = await import('./codex-sessions')
    const first = child(); mocks.spawn.mockReturnValue(first)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const opts = { projectPath: mocks.directory, prompt: 'first', access: 'read-only' as const }
    const session = api.startCodexTurn(opts)
    api.startCodexTurn({ ...opts, sessionId: session.id, prompt: 'next' })
    first.emit('close', 1)
    expect(session.queuePaused).toBe(true)
    const pendingId = session.pendingTurns![0].id
    api.controlCodexQueue(session.id, 'remove', pendingId)
    expect(session.pendingTurns).toEqual([])
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
  })
})

describe('automatic restart recovery', () => {
  it('resumes an interrupted request before draining its queue without duplicating the user message', async () => {
    let api = await import('./codex-sessions')
    const first = child(); mocks.spawn.mockReturnValue(first)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const s = api.startCodexTurn({ projectPath: mocks.directory, prompt: 'render shot', access: 'workspace-write', model: 'model-a', effort: 'high' })
    first.stdout.write('{"type":"thread.started","thread_id":"resume-thread"}\n{"type":"turn.started"}\n')
    api.startCodexTurn({ projectPath: mocks.directory, sessionId: s.id, prompt: 'add blur', access: 'workspace-write' })
    const messageId = s.messages[0].id
    api.shutdownCodexSessions(); first.emit('close', 1)
    expect(s.queuePaused).toBe(false)
    expect(s.resumeOnRestart).toBe(true)
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
    vi.resetModules(); api = await import('./codex-sessions')
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const resumed = child(); mocks.spawn.mockReturnValue(resumed)
    await api.recoverCodexSessions()
    const recovered = api.getCodexSessions()[0]
    expect(recovered.messages).toHaveLength(1)
    expect(recovered.messages[0].id).toBe(messageId)
    expect(recovered.pendingTurns?.[0].options.prompt).toBe('add blur')
    expect(mocks.spawn.mock.calls[1][1]).toEqual(expect.arrayContaining(['resume', 'resume-thread', '--model', 'model-a']))
    expect(resumed.stdin.read().toString()).toContain('preserve completed work')
    resumed.stdout.write('{"type":"turn.started"}\n')
    expect(recovered.messages[0].state).toBe('working')
    mocks.spawn.mockReturnValue(child())
    resumed.stdout.write('{"type":"turn.completed"}\n'); resumed.emit('close', 0)
    expect(recovered.messages.map(m => m.content)).toEqual(['render shot', 'add blur'])
    expect(recovered.messages[0].state).toBe('completed')
    expect(mocks.spawn).toHaveBeenCalledTimes(3)
  })

  it('does not repeat a completed turn when the app crashes before process close', async () => {
    let api = await import('./codex-sessions')
    const first = child(); mocks.spawn.mockReturnValue(first)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const s = api.startCodexTurn({ projectPath: mocks.directory, prompt: 'first', access: 'read-only' })
    api.startCodexTurn({ projectPath: mocks.directory, sessionId: s.id, prompt: 'second', access: 'read-only' })
    first.stdout.write('{"type":"turn.completed"}\n')
    vi.resetModules(); api = await import('./codex-sessions')
    api.initCodexSessions({ isDestroyed: () => true } as any)
    mocks.spawn.mockReturnValue(child())
    await api.recoverCodexSessions()
    expect(api.getCodexSessions()[0].messages.map(m => m.content)).toEqual(['first', 'second'])
    expect(mocks.spawn).toHaveBeenCalledTimes(2)
  })

  it('leaves real failures paused instead of repeatedly retrying them', async () => {
    let api = await import('./codex-sessions')
    const first = child(); mocks.spawn.mockReturnValue(first)
    api.initCodexSessions({ isDestroyed: () => true } as any)
    const s = api.startCodexTurn({ projectPath: mocks.directory, prompt: 'first', access: 'read-only' })
    api.startCodexTurn({ projectPath: mocks.directory, sessionId: s.id, prompt: 'second', access: 'read-only' })
    first.emit('close', 1)
    vi.resetModules(); api = await import('./codex-sessions')
    api.initCodexSessions({ isDestroyed: () => true } as any)
    await api.recoverCodexSessions()
    expect(mocks.spawn).toHaveBeenCalledTimes(1)
    expect(api.getCodexSessions()[0].pauseReason).toBe('error')
  })
})
